version: '3.8'

services:
  nats:
    image: nats:2.10.16-alpine3.19
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js
    environment:
      - JS_STORAGE_DIR=/data/jetstream
    volumes:
      - ./nats/data:/data

  main:
    container_name: finding_forwarder
    build: ./
    restart: always
    command:
      - ./bin/main
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OPSGENIE_API_KEY=${OPSGENIE_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NATS_DEFAULT_URL=${NATS_DEFAULT_URL}
      - BOT_CONTAINERS==${BOT_CONTAINERS}
    ports:
      - '8080:8080'
    depends_on:
      - nats