version: '3.8'

services:
  nats:
    image: nats:2.10.16-alpine3.19
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js
    environment:
      - JS_STORAGE_DIR=/data/jetstream
    volumes:
      - ./nats/data:/data

  main:
    container_name: finding_forwarder
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - nats

networks:
  postgres:
    driver: bridge