version: '3.8'
x-logging: &default-logging
  options:
    max-size: "50m"
    max-file: "10"

services:
  service-forta-nats:
    image: nats:2.10.20-alpine3.20
    container_name: forta-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js
    environment:
      - JS_STORAGE_DIR=/data/jetstream
    volumes:
      - ./nats/data:/data

  service-forta-json-rpc:
    container_name: forta-json-rpc
    logging: *default-logging
    image: forta-network/forta-node:latest
    command: /forta-node json-rpc
    ports:
      - 8545:8545
    volumes:
      - ./forta-local-config.yml:/.forta/config.yml
    depends_on:
      - service-forta-nats

  service-forta-scanner:
    container_name: forta-scanner
    logging: *default-logging
    image: forta-network/forta-node:latest
    command: /forta-node scanner
    volumes:
      - ./forta-local-config.yml:/.forta/config.yml
    depends_on:
      - service-forta-nats
      - service-forta-json-rpc
      - service-ethereum-steth

  forwarder-server:
    container_name: finding-forwarder-server
    build: ./
    restart: always
    command:
      - ./main
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OPSGENIE_API_KEY=${OPSGENIE_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NATS_DEFAULT_URL=${NATS_DEFAULT_URL}
      - BOT_CONTAINERS=${BOT_CONTAINERS}
    ports:
      - '8080:8080'

  forwarder-worker:
    container_name: finding-forwarder-worker
    build: ./
    restart: always
    command:
      - ./worker
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OPSGENIE_API_KEY=${OPSGENIE_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NATS_DEFAULT_URL=${NATS_DEFAULT_URL}
      - BOT_CONTAINERS=${BOT_CONTAINERS}
    ports:
      - '8081:8080'

  service-ethereum-steth:
    container_name: ethereum-steth
    logging: *default-logging
    image: monitoring/steth:latest
    restart: unless-stopped
    environment:
      - APP_NAME=ethereum-steth
      - INSTANCE=forta-local-host
      - ETHEREUM_RPC_URL=http://forta-json-rpc:8545
      - USE_FORTA_RPC_URL=false
      - NODE_ENV=production
      - NATS_SERVER_URL=http://forta-nats:4222
    depends_on:
      - service-forta-json-rpc
      - service-forta-nats
    ports:
      - '3001:3000'

  service-l2-bridge-arbitrum:
    container_name: l2-bridge-arbitrum
    logging: *default-logging
    image: monitoring/l2-bridge-arbitrum:latest
    restart: unless-stopped
    environment:
      - APP_NAME=l2-bridge-arbitrum
      - INSTANCE=forta-local-host
      - ETHEREUM_RPC_URL=http://forta-json-rpc:8545
      - ARBITRUM_RPC_URL=https://arbitrum-one.blastapi.io/<you_api_ley>
      - USE_FORTA_RPC_URL=false
      - NODE_ENV=production
    depends_on:
      - service-forta-json-rpc
    ports:
      - '3002:3000'