chainId: 1

scan:
  jsonRpc:
    url: https://eth.drpc.org

localMode:
  enable: true
  logToStdout: true
  privateKeyHex: 984d28fde238c32d06420db29b7277f5fd24c61954d2da491bf7d1ef19996bd0
  # webhookUrl: http://host.docker.internal:8080/alerts
  webhookUrl: http://finding-forwarder-server:8080/alerts
  standalone:
    enable: true
    botContainers:
      - host.docker.internal
      - ethereum-steth