creation_rules:
  - path_regex: .+\.sops
    # ci_user
    # amarao
    # n0guest
    # choooze
    # ramiz
    # Vitaliy
    # br3d
    pgp: >-
      29C2437B21040E4C42495860FE911AF12E3C9E7B,
      24DCC5AB5D0CA136A3AE9482D9A1B02691B1E099,
      06348F9B5E4BFD92F15BA4ED20D02B2EBD52FF10,
      5F5B703D1DE90A7C9DBF0F006A7B481646FCE44A,
      C4EF83E6B5FBE679FAD9D360E79FA66C2EE0F5B0,
      A662E65120C17FF48BBA40CB45376E6F3E17240B,
      31656B2D13C087CEC097545C0AC52C72762AABB2

# CI public key can't be published in keyring (there is no email)
# 29C2437B21040E4C42495860FE911AF12E3C9E7B
# Github secret name: SOPS_PRODUCTION
# -----BEGIN PGP PUBLIC KEY BLOCK-----
#
# mQINBGasqdIBEAC+Re3kAh2sD/JB69qjzbqd8Y0OskJ5H4HncoTa0nH/wTvJAQIW
# Vj0XLwvmO0dxKsN0+5O9sbmvl9mleJ4XvYuACxSLPZIK1rzbF0ieAH95QvohKdki
# l38rY8rGwP2bSL8T7lHqTTdl+5zWqknGuQhePzSMmjcuDafDxhsZRtTQ91e4ugWi
# FWJ5IkFEi9QnB+hVFHcNXon0KXeLd2l23YHrrBhzt0z+QgR5RQKESxqvwrPMULI7
# yF9ReknwioOtzKI6ICR6eEzLFPUhPI1ZvfxK7D6CufN4dz+OZcogNAKhc5MuapIx
# 6HPQyIRcN43AtCZN4V12ZksYQmdQa+P4+Yz2Hc5+UX62ELXjCJ6OiKDjgdZtkyma
# uPvEY0NuEJh4+U2s64D4dX3dD9Gd86ZXquZhoB6JXZr/ORl+VyZaYHmLXp2VCQRr
# RBypAACrNaxc7AE4Gp4NQTuh6P9LrQf7Pr9/s5DDPY0jHVz+MjDks0dphn1CrPiq
# Y18KrrsVLl9E6qy7oov6XKEMbUh3WkDqmUYv6TuFgxfMB01sAiVDJtWmHrgVEYdq
# si9KBhrWsbx9QsnRiI+TB006mR/hj2aeSLNaQmiL0LJXhR17OdmcGnPL+ZO2KLQG
# 2dv5toKaD9zHItXMkQlunKzPect3V6/RzaT96ZE78qWRp4Nz3pHhHDskIQARAQAB
# tAdjaV91c2VyiQJOBBMBCgA4FiEEKcJDeyEEDkxCSVhg/pEa8S48nnsFAmasqdIC
# GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQ/pEa8S48nntrlQ//cfEr6xcJ
# IVF9h0bomGWgqfrbksroHjWZMqDBqES2LtOw2UNeM+xG/qRmWsGnyWOj8liUKzua
# 0/VR+6Bx5UrfqqJYUc0wwE+269khEoiss3sMO0iw7JhnYplIQimZIMsiEek3gpgM
# ZgWp7mDxXBjPY6ZDdcIurEH0At8fnVtHkUNW4DTGNgMNQeLpTFhv1mAEXl+IF4N1
# E17Ky6D5BejTIc91998xsWmseImAKkbQ5grQhCWtfdyly3ERfrh/4I0KT1ndh+JJ
# aGBVptIlabwrs/NbjhN8v9gkJs0OGSTmuvsSe9nl9GjTc3l4NVYSrj7q6boeaRgN
# STzIO109hbOF0AvE6P6OAXOzIj0wWGkW1nodH79SeSRFggHGWdf6MYYgjcD1iYyo
# p/IG3tfFmrxYmvhJDuGg9eFKoLo+8gCWfhuUIwRpr8+zgnNnSX6hqSbyc+1hOlac
# v/pWsrHV+Tovu210UQW4884vMBlAUVuJhOhl6buu06lZEm6JlrFGqWcJ/uymvH4x
# uTc8Z+Q/yW1Jo6JRrscAUBPAKQpgZY9bK+of5Pgti9xlmGjHGrC4AqyN6HqoxnQt
# 1Hx0IxX7R8HSecWgklXn5sN0lAubHkNu2OnZ6Pf09arSQhpfEe+sqIIZU1X7Acw6
# FCARmruojRrXCZ2wMzh+S4ogbScKab76pJ65Ag0EZqyp0gEQAMkeu2K5NwYiWmKB
# CMQnMzYE617UgUFP+skOnYE2D3omMS3ZWEEGpdaH5LPORHkhf862xxZYlI5IlAte
# SRjyeDrwDXI7wWnDo7UIXJKQkBx9bNXBvEGq768x38plGACrPjadLJ2UOMBSHi53
# Abqp2LVZIj4YdHSQcYopw+8lyu9mfM1SoonwbT7Iha3jRWV0NgaS7T43OFATVWZY
# 3Upg/ZYdjCcNsDawIepgZGFfieGox3QsyN0lz9Axbe5L5oYcHJP5c9FFR/KPbVXx
# MEdWsnNitTJcUgS5CAky1o3fMUZb1qoxJpCLAqDJtg7kY2ST3Ja7e5GmsGtSwyto
# t56go1E9Yxfg2jIjTqOqO/lAJRUEvXm30NoCUU1KVS5DRkvuo7C9bZpSuCh4n+5O
# Ok6wpLdAj+ak+yfEv5boJxdurRjjx+jen+WgKCACu57+alEKEgs/9GK5Tup/WREy
# OuzqNIobDuS5A+6UGCd+jCyZ47T9efnk+iyhFTyJB1Pyjt+oh/egEyHwFZZMOcsc
# tQ/uYe6NYJfEnEZb+KQDyCKVUcaPevbg0syn3Vb9V168neICvD+WXs+Xv1PxGK8M
# YKIDuF6QA5jYP4wSvd94pm31URnh4vTra2/cdWV30RgSZQ2yYUHRv8CWPWGOQSDI
# 6sL2WwaF+sFbS/hY7PQdITdLB+qjABEBAAGJAjYEGAEKACAWIQQpwkN7IQQOTEJJ
# WGD+kRrxLjyeewUCZqyp0gIbDAAKCRD+kRrxLjyeeynjEACEQwezA9pIIwujTxZZ
# +x3Oull+MVES2mg7Sl4Jwmvce4eUaq0XaLKbaUUth7fXUtgS7Qq1/dxP9S3ccjvb
# gg5bHi1ppHkPpWUQlyZICF25TBpV38eJDKrhXMLguZVb4KFt83DmEZztUSi+9uRn
# iczq483Xhl8BiduMRZCLw91BWD3+h5qXFa+gAfVWbQy3Xe+aZldSTGukhyvSwsiR
# cblj/bIVUArW9a9li2SgNZszFI6JLKstslsxXhQ651EfLwc0G2pulcsj39RPpAPV
# Ld4D3ML2O/kalcCncaceAhpquSH52tfFkrWxw+qO8RsKAU6w5a7a5vJQ1I/z8gur
# GdVSXCcr6K2KoJo8OR2lhR64XPPaDtc63ko/C95UXPi3yVUyvVuy4LMbGZdigxpV
# Jbg7zDoOVJoYhOWXDs+lr8PUT8bYxgYn8XHqHLdbXQ0QEYuMSOrsZtg3xNeQF2Fd
# Azl6klqt2O5LLZIPKrQN38/m/Y8F1s4vOKjlicAXfUUu2HyI51bcurHOoLsxkww9
# KX2jNUF+YYYvxAhRSQQ+ioj26CmiuT5IYMCaT2we4x9WHn/6IjODZEmrmOcvJ6LC
# ZLorkEkNi0ZZSe/opqVbQVGTBU94aqcnaRPjM2QswlZ283v8A4Fg9SuRuqydAvJM
# LNp8PoqqqIwxAGd6xHjuFa5XFg==
# =ykYJ
# -----END PGP PUBLIC KEY BLOCK-----
