---
name: Build and release production image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: forta-finding-forwarder
  IMAGE_TAG: stable
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_INVENTORY: inventories/production/,provider_inventories/production/,inventories/ci_user.yml
  encrypted_ssh_key: .github/secrets/production/ssh_private_key.sops
  encrypted_ci_env: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        id: docker_build_candidate
        uses: docker/build-push-action@v6.1.0
        with:
          push: true
          tags: lidofinance/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}

  deploy:
    needs:
      - build-and-push
    concurrency:
      group: onchain_mon
      cancel-in-progress: false
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/lidofinance/ci:stable
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Open sops secrets
        uses: ./.github/actions/import_sops_secrets
        with:
          sops_key: ${{ env.sops_key }}
          encrypted_ssh_key: ${{ env.encrypted_ssh_key }}
          encrypted_ci_env: ${{ env.encrypted_ci_env }}

      - name: Deploy on production
        run: ansible-playbook
          playbooks/main.yml
          -e github_username=${{ github.actor }}
        working-directory: ansible
        shell: bash
